[package]
name = "game_of_life"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terminal_graphics = "0.1.5"

[[bin]]
name = "game_of_life"
path = "src/main.rs"
